export const ADD_TO_STATICS = 'ADD_TO_STATICS';
export const REDRAW_STATE_ELEMENT = 'REDRAW_STATE_ELEMENT';
export const UPDATE_AFTER_REMOVE = 'UPDATE_AFTER_REMOVE';
export const PUSH_OBJ_AFTER_REMOVE = 'PUSH_OBJ_AFTER_REMOVE';
export const LAST_FINISHED_CARD = 'LAST_FINISHED_CARD';
export const PAUSE_CARD = 'PAUSE_CARD';
export const SHOW_REJECTED_LIST = 'SHOW_REJECTED_LIST';
export const NEW_CARD_TIME_TO_START = 'NEW_CARD_TIME_TO_START';